### PR TITLE
Added Azure Token Provider

### PR DESCRIPTION
**Pull request by arraintxo**
As Microsoft DataMarket services are being deprecated, an upgrade to Azure keys is needed.
This pull request provides a new Azure Token Provider that easies this transition.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
I'm sorry, missed this PR. I'm not actively maintaining this library to be honest. Would you by chance be interested in taking this role?

**Comment by arraintxo** [comment]
I'm using it on an active project, if new changes or bugfixes are needed I should take care of them, so I wouldn't mind trying to take the role.

**Comment by matthiasnoback** [comment]
Excellent! I'll give you GitHub permissions to work on it right-away. You could start with merging your own PR.
Are you familiar with package maintenance? Like tagging, semantic versioning, etc.? I'd be happy to help out with any question you may have.

**Comment by arraintxo** [comment]
I have some knowledge about it, I know how tagging and semantic versioning work, but have no real world experience on package maintenance.

I will do it as well as I can :)

**Comment by matthiasnoback** [comment]
That's great! Best of luck then :)

**Pull request merged**
